//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2012.02.08 at 02:47:44 PM GMT
//

package org.jclouds.vcloud.director.v1_5.domain;

import static org.jclouds.vcloud.director.v1_5.VCloudDirectorConstants.*;

import java.util.ArrayList;
import java.util.List;

import javax.xml.bind.annotation.XmlAnyElement;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;

import org.jclouds.vcloud.director.v1_5.domain.ovf.SectionType;
import org.jclouds.vcloud.director.v1_5.domain.ovf.StartupSectionItem;
import org.jclouds.vcloud.director.v1_5.domain.ovf.SectionType.Builder;

/**
 * Specifies the order in which entities in a VirtualSystemCollection are powered on and shut down
 *
 * <pre>
 * &lt;complexType name="StartupSection_Type" /&gt;
 * </pre>
 */
@XmlRootElement(name = "StartupSection", namespace = VCLOUD_OVF_NS)
public class StartupSection extends SectionType<StartupSection> {

   /** @see org.jclouds.vcloud.director.v1_5.domain.ovf.SectionType#toBuilder() */
   @Override
   public org.jclouds.vcloud.director.v1_5.domain.ovf.SectionType.Builder<StartupSection> toBuilder() {
      return null;
   }

   @XmlElement(name = "Item")
   protected List<StartupSectionItem> item;
   @XmlAnyElement(lax = true)
   protected List<Object> any;

   /**
    * Gets the value of the item property.
    * <p>
    * This accessor method returns a reference to the live list, not a snapshot. Therefore any modification you make to the returned
    * list will be present inside the JAXB object. This is why there is not a <CODE>set</CODE> method for the item property.
    * <p>
    * For example, to add a new item, do as follows:
    *
    * <pre>
    * getItem().add(newItem);
    * </pre>
    * <p>
    * Objects of the following type(s) are allowed in the list {@link StartupSectionItem }
    */
   public List<StartupSectionItem> getItem() {
      if (item == null) {
         item = new ArrayList<StartupSectionItem>();
      }
      return this.item;
   }

   /**
    * Gets the value of the any property.
    * <p>
    * This accessor method returns a reference to the live list, not a snapshot. Therefore any modification you make to the returned
    * list will be present inside the JAXB object. This is why there is not a <CODE>set</CODE> method for the any property.
    * <p>
    * For example, to add a new item, do as follows:
    *
    * <pre>
    * getAny().add(newItem);
    * </pre>
    * <p>
    * Objects of the following type(s) are allowed in the list {@link Object } {@link Element }
    */
   public List<Object> getAny() {
      if (any == null) {
         any = new ArrayList<Object>();
      }
      return this.any;
   }
}
