/**
 *
 * Copyright (C) 2009 Cloud Conscious, LLC. <info@cloudconscious.com>
 *
 * ====================================================================
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 * ====================================================================
 */
package org.jclouds.compute.domain;

import org.jclouds.compute.domain.internal.ComputeMetadataImpl;
import org.jclouds.domain.ResourceMetadata;

import com.google.inject.ImplementedBy;

/**
 * @author Ivan Meredith
 * @author Adrian Cole
 */
@ImplementedBy(ComputeMetadataImpl.class)
public interface ComputeMetadata extends ResourceMetadata<ComputeType> {
   /**
    * Type of the resource, ex node, image, size
    * 
    */
   @Override
   public ComputeType getType();

   /**
    * unique id of the server. potentially generated by the service.
    * 
    */
   @Override
   public String getId();

   /**
    * user defined name of the server.
    * 
    */
   @Override
   public String getName();

   /**
    * location where the node exists..
    * 
    */
   @Override
   public String getLocation();

}
