/**
 * Licensed to jclouds, Inc. (jclouds) under one or more
 * contributor license agreements.  See the NOTICE file
 * distributed with this work for additional information
 * regarding copyright ownership.  jclouds licenses this file
 * to you under the Apache License, Version 2.0 (the
 * "License"); you may not use this file except in compliance
 * with the License.  You may obtain a copy of the License at
 *
 *   http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing,
 * software distributed under the License is distributed on an
 * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 * KIND, either express or implied.  See the License for the
 * specific language governing permissions and limitations
 * under the License.
 */
package org.jclouds.cloudwatch.options;

import com.google.common.annotations.Beta;
import com.google.common.base.Preconditions;
import com.google.common.collect.Sets;
import org.jclouds.cloudwatch.domain.Dimension;
import org.jclouds.cloudwatch.domain.Statistics;
import org.jclouds.cloudwatch.domain.Unit;
import org.jclouds.date.DateService;
import org.jclouds.date.internal.SimpleDateFormatDateService;
import org.jclouds.http.options.BaseHttpRequestOptions;
import org.jclouds.javax.annotation.Nullable;

import java.util.Date;
import java.util.Set;

/**
 * Options use to get statistics for the specified metric.
 *
 * @see <a href="http://docs.amazonwebservices.com/AmazonCloudWatch/latest/APIReference/API_GetMetricStatistics.html" />
 *
 * @author Jeremy Whitlock
 */
@Beta
public class GetMetricStatisticsOptionsV2 extends BaseHttpRequestOptions {

   private static final DateService dateService = new SimpleDateFormatDateService();
   private final Set<Dimension> dimensions;
   private final Date endTime;
   private final String metricName;
   private final String namespace;
   private final int period;
   private final Date startTime;
   private final Set<Statistics> statistics;
   private final Unit unit;

   /**
    * Private constructor to enforce using {@link Builder}.
    */
   private GetMetricStatisticsOptionsV2(@Nullable Set<Dimension> dimensions, Date endTime, String metricName,
                                        String namespace, int period, Date startTime, Set<Statistics> statistics,
                                        Unit unit) {
      this.dimensions = dimensions;
      this.endTime = endTime;
      this.metricName = metricName;
      this.namespace = namespace;
      this.period = period;
      this.startTime = startTime;
      this.statistics = statistics;
      this.unit = unit;
   }

   /**
    * return the set of dimensions for this request
    */
   @Nullable
   public Set<Dimension> getDimensions() {
      return dimensions;
   }

   /**
    * return the end time for this request
    */
   public Date getEndTime() {
      return endTime;
   }

   /**
    * return the metric name for this request
    */
   public String getMetricName() {
      return metricName;
   }

   /**
    * return the namespace for this request
    */
   public String getNamespace() {
      return namespace;
   }

   /**
    * return the period for this request
    */
   public int getPeriod() {
      return period;
   }

   /**
    * return the start time for this request
    */
   public Date getStartTime() {
      return startTime;
   }

   /**
    * return the statistics for this request
    */
   public Set<Statistics> getStatistics() {
      return statistics;
   }

   /**
    * return the unit for this request
    */
   public Unit getUnit() {
      return unit;
   }

   /**
    * Returns a new builder. The generated builder is equivalent to the builder
    * created by the {@link Builder} constructor.
    */
   public static Builder builder() {
      return new Builder();
   }

   public static class Builder {

      private Set<Dimension> dimensions = Sets.newLinkedHashSet();
      private Date endTime;
      private String metricName;
      private String namespace;
      private int period;
      private Date startTime;
      private Set<Statistics> statistics = Sets.newLinkedHashSet();
      private Unit unit;

      /**
       * Creates a new builder. The returned builder is equivalent to the builder
       * generated by {@link ListMetricsOptions#builder}.
       */
      public Builder() {}

      /**
       * A list of dimensions describing qualities of the metric.  (Set can be 10 or less items.)
       *
       * @param dimensions the dimensions describing the qualities of the metric
       *
       * @return this {@code Builder} object
       *
       * @throws IllegalArgumentException if this is invoked more than 10 times
       */
      public Builder dimensions(Set<Dimension> dimensions) {
         if (dimensions != null) {
            Preconditions.checkArgument(dimensions.size() <= 10, "dimensions can have 10 or fewer members.");
            this.dimensions = dimensions;
         }
         return this;
      }

      /**
       * A dimension describing qualities of the metric.  (Can be called multiple times up to a maximum of 10 times.)
       *
       * @param dimension the dimension describing the qualities of the metric
       *
       * @return this {@code Builder} object
       *
       * @throws IllegalArgumentException if the number of dimensions would be greater than 10 after adding
       */
      public Builder dimension(Dimension dimension) {
         if (dimension != null) {
            Preconditions.checkArgument(dimensions.size() < 10, "dimension member maximum count of 10 exceeded.");
            this.dimensions.add(dimension);
         }
         return this;
      }

      /**
       * The time stamp to use for determining the last datapoint to return. The value specified is exclusive so
       * results will include datapoints up to the time stamp specified.  (Should be called once.  Subsequent calls
       * will overwrite the previous value.)
       *
       * @param endTime the timestamp to use for determining the last datapoint to return
       *
       * @return this {@code Builder} object
       *
       * @throws NullPointerException if endTime is null
       */
      public Builder endTime(Date endTime) {
         Preconditions.checkNotNull(endTime, "endTime cannot be null.");
         this.endTime = endTime;
         return this;
      }

      /**
       * The name of the metric.  (Should be called once.  Subsequent calls will overwrite the previous value.)
       *
       * @param metricName the metric name to filter against
       *
       * @return this {@code Builder} object
       *
       * @throws NullPointerException if metricName is null
       * @throws IllegalArgumentException if metricName is empty
       */
      public Builder metricName(String metricName) {
         Preconditions.checkNotNull(metricName, "metricName cannot be null.");
         Preconditions.checkArgument(metricName.length() > 1, "metricName must not be empty.");
         this.metricName = metricName;
         return this;
      }

      /**
       * The namespace of the metric.  (Should be called once.  Subsequent calls will overwrite the previous value.
       * See {@link org.jclouds.cloudwatch.domain.Namespaces} for the known list of namespaces.)
       *
       * @param namespace the namespace to filter against
       *
       * @return this {@code Builder} object
       *
       * @throws NullPointerException if namespace is null
       * @throws IllegalArgumentException if namespace is empty
       */
      public Builder namespace(String namespace) {
         Preconditions.checkNotNull(namespace, "namespace cannot be null.");
         Preconditions.checkArgument(namespace.length() > 1, "namespace must not be empty.");
         this.namespace = namespace;
         return this;
      }

      /**
       * The granularity, in seconds, of the returned datapoints. Period must be at least 60 seconds and must be a
       * multiple of 60. The default value is 60.  (Should be called once.  Subsequent calls will overwrite the
       * previous value.)
       *
       * @param period the granularity, in seconds, of the returned datapoints
       *
       * @return this {@code Builder} object
       *
       * @throws NullPointerException if period is null
       * @throws IllegalArgumentException if period is less than 60 or not a multiple of 60
       */
      public Builder period(int period) {
         Preconditions.checkNotNull(period, "period cannot be null.");
         Preconditions.checkArgument(period >= 60 && period % 60 == 0, "period must be greater than 60 and as a " +
               "multiple of 60.");
         this.period = period;
         return this;
      }

      /**
       * The time stamp to use for determining the first datapoint to return. The value specified is inclusive so
       * results include datapoints with the time stamp specified.  (Should be called once.  Subsequent calls will
       * overwrite the previous value.)
       *
       * @param startTime The time stamp to use for determining the first datapoint to return
       *
       * @return this {@code Builder} object
       *
       * @throws NullPointerException if startTime is null
       */
      public Builder startTime(Date startTime) {
         Preconditions.checkNotNull(startTime, "startTime cannot be null.");
         this.startTime = startTime;
         return this;
      }

      /**
       * The metric statistics to return.  (Should be called once.  Subsequent calls will overwrite the previous
       * value.)
       *
       * @param statistics the metric statistics to return.
       *
       * @return this {@code Builder} object
       *
       * @throws IllegalArgumentException if the number of statistics is greater than 5
       * @throws NullPointerException if statistics is null
       */
      public Builder statistics(Set<Statistics> statistics) {
         Preconditions.checkNotNull(statistics, "statistics cannot be null.");
         Preconditions.checkArgument(statistics.size() <= 5, "statistics can have 5 or fewer members.");
         this.statistics = statistics;
         return this;
      }

      /**
       * The metric statistic to return.  (Can be called multiple times up to a maximum of 5 times.)
       *
       * @param statistic the metric statistic to return
       *
       * @return this {@code Builder} object
       *
       * @throws IllegalArgumentException if the number of statistics would be greater than 5 after adding
       * @throws NullPointerException if statistic is null
       */
      public Builder statistic(Statistics statistic) {
         Preconditions.checkNotNull(statistic, "statistic cannot be null.");
         Preconditions.checkArgument(statistics.size() < 5, "statistics member maximum count of 5 exceeded.");
         this.statistics.add(statistic);
         return this;
      }

       /**
        * The unit for the metric.  (Should be called once.  Subsequent calls will overwrite the previous value.)
        *
        * @param unit the unit for the metric
        *
        * @return this {@code Builder} object
        *
        * @throws NullPointerException if unit is null
        */
      public Builder unit(Unit unit) {
         Preconditions.checkNotNull(unit, "unit cannot be null.");
         this.unit = unit;
         return this;
      }

      /**
       * Returns a newly-created {@code GetMetricStatisticsOptionsV2} based on the contents of
       * the {@code Builder}.
       *
       * @throws NullPointerException if any of the required fields are null
       * @throws IllegalArgumentException if any of the provided fields don't meet required criteria
       */
      public GetMetricStatisticsOptionsV2 build() {
         Preconditions.checkNotNull(endTime, "endTime cannot be null.");
         Preconditions.checkNotNull(metricName, "metricName cannot be null.");
         Preconditions.checkNotNull(namespace, "namespace cannot be null.");
         Preconditions.checkNotNull(period, "period cannot be null.");
         Preconditions.checkNotNull(startTime, "startTime cannot be null.");
         Preconditions.checkNotNull(statistics, "statistics cannot be null.");
         Preconditions.checkNotNull(unit, "unit cannot be null.");
         Preconditions.checkArgument(statistics.size() >= 1, "statistics must have at least one member");

         GetMetricStatisticsOptionsV2 options = new GetMetricStatisticsOptionsV2(dimensions, endTime, metricName,
                                                                                 namespace, period, startTime,
                                                                                 statistics, unit);
         int dimensionIndex = 1;
         int statisticIndex = 1;

         for (Dimension dimension : dimensions) {
            options.formParameters.put("Dimensions.member." + dimensionIndex + ".Name", dimension.getName());
            options.formParameters.put("Dimensions.member." + dimensionIndex + ".Value", dimension.getValue());
            dimensionIndex++;
         }

         options.formParameters.put("EndTime", dateService.iso8601SecondsDateFormat(endTime));
         options.formParameters.put("MetricName", metricName);
         options.formParameters.put("Namespace", namespace);
         options.formParameters.put("Period", Integer.toString(period));
         options.formParameters.put("StartTime", dateService.iso8601SecondsDateFormat(startTime));

         for (Statistics statistic : statistics) {
            options.formParameters.put("Statistics.member." + statisticIndex, statistic.toString());
            statisticIndex++;
         }

         options.formParameters.put("Unit", unit.toString());

         return options;
      }

   }

}
