/**
 * Licensed to jclouds, Inc. (jclouds) under one or more
 * contributor license agreements.  See the NOTICE file
 * distributed with this work for additional information
 * regarding copyright ownership.  jclouds licenses this file
 * to you under the Apache License, Version 2.0 (the
 * "License"); you may not use this file except in compliance
 * with the License.  You may obtain a copy of the License at
 *
 *   http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing,
 * software distributed under the License is distributed on an
 * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 * KIND, either express or implied.  See the License for the
 * specific language governing permissions and limitations
 * under the License.
 */
package org.jclouds.cloudwatch.options;

import org.jclouds.cloudwatch.domain.Dimension;
import org.jclouds.http.options.BaseHttpRequestOptions;
import org.jclouds.javax.annotation.Nullable;

import java.util.LinkedHashSet;
import java.util.Set;

/**
 * Options used to list available metrics.
 *
 * @see <a href="http://docs.amazonwebservices.com/AmazonCloudWatch/latest/APIReference/API_ListMetrics.html" />
 *
 * @author Jeremy Whitlock
 */
public class ListMetricsOptions extends BaseHttpRequestOptions {

   private final Set<Dimension> dimensions;
   private final String metricName;
   private final String namespace;
   private final String nextToken;

   /**
    * Private constructor to enforce using {@link Builder}.
    */
   private ListMetricsOptions(@Nullable String namespace, @Nullable String metricName,
                              @Nullable Set<Dimension> dimensions, @Nullable String nextToken) {
      this.dimensions = dimensions;
      this.metricName = metricName;
      this.namespace = namespace;
      this.nextToken = nextToken;
   }

   /**
    * return the set of dimensions for this request
    */
   @Nullable
   public Set<Dimension> getDimensions() {
      return dimensions;
   }

   /**
    * return the metric name for this request
    */
   @Nullable
   public String getMetricName() {
      return metricName;
   }

   /**
    * return the namespace for this request
    */
   @Nullable
   public String getNamespace() {
      return namespace;
   }

   /**
    * return the next token for this request
    */
   @Nullable
   public String getNextToken() {
      return nextToken;
   }

   /**
    * Returns a new builder. The generated builder is equivalent to the builder
    * created by the {@link Builder} constructor.
    */
   public static Builder builder() {
      return new Builder();
   }

   public static class Builder {

      private Set<Dimension> dimensions = new LinkedHashSet<Dimension>();
      private String metricName;
      private String namespace;
      private String nextToken;

      /**
       * Creates a new builder. The returned builder is equivalent to the builder
       * generated by {@link ListMetricsOptions#builder}.
       */
      public Builder() {}

      /**
       * Filter available metrics specific to the namespace provided.  To get all metrics regardless of the namespace,
       * do not use this builder option.  Only one namespace can be specified at a time so multiple invocations of
       * this will just overwrite what was set prior.  Available AWS namespaces are listed in the
       * {@link org.jclouds.cloudwatch.domain.Namespaces} class.  You can also use custom namespaces if you've
       * configured CloudWatch for such things.
       *
       * @param namespace the namespace to filter the returned metrics by
       *
       * @return this {@code Builder} object
       */
      public Builder namespace(String namespace) {
         this.namespace = namespace;
         return this;
      }

      /**
       * Filter available metrics specific to the provided metric name.  To get all metrics regardless of the metric
       * name, do not use this builder option.  Only one namespace can be specified at a time so multiple invocations
       * of this will just overwrite what was set prior.  Available AWS metric names are listed in the
       * org.jclouds.cloudwatch.domain.*Constants classes and are AWS product specific.  You can also use custom
       * metric names if you've configured CloudWatch for such things.
       *
       * @param metricName the metric name to filter the returned metrics by
       *
       * @return this {@code Builder} object
       */
      public Builder metricName(String metricName) {
         this.metricName = metricName;
         return this;
      }

      /**
       * Same as {@link #dimension(org.jclouds.cloudwatch.domain.Dimension)} but replaces the current set of
       * dimensions with the one passed in.
       *
       * @see #dimension(org.jclouds.cloudwatch.domain.Dimension)
       */
      public Builder dimensions(Set<Dimension> dimensions) {
         if (dimensions.size() > 10) {
            throw new IllegalArgumentException("The maximum number of dimensions for ListOptions is 10.");
         }
         this.dimensions = dimensions;
         return this;
      }

      /**
       * Filter available metrics based on the {@link Dimension} passed in.  To get all metrics regardless of the
       * dimension, do not use this builder option.  You can specify up to 10 different dimensions per request.
       * Available AWS dimensions are listed in the org.jclouds.cloudwatch.domain.*Constants classes and are AWS
       * product specific.  You can also use custom dimensions if you've configured CloudWatch for such things.
       *
       * @param dimension the dimension to filter the returned metrics by
       *
       * @return this {@code Builder} object
       *
       * @throws IllegalArgumentException if this is invoked more than 10 times
       */
      public Builder dimension(Dimension dimension) {
         if (dimension != null) {
            if (this.dimensions.size() >= 10) {
               throw new IllegalArgumentException("You have exceeded the maximum number of dimensions per " +
                                                  "request.");
            }
            this.dimensions.add(dimension);
         }
         return this;
      }

      /**
       * Specify that this request is a follow-up to retrieve more data from a paginated request.
       *
       * @param nextToken the next token
       *
       * @return this {@code Builder} object
       */
      public Builder nextToken(String nextToken) {
         this.nextToken = nextToken;
         return this;
      }

      /**
       * Returns a newly-created {@code ListMetricsOptions} based on the contents of
       * the {@code Builder}.
       */
      public ListMetricsOptions build() {
         ListMetricsOptions lmo = new ListMetricsOptions(namespace, metricName, dimensions, nextToken);
         int dimensionIndex = 1;

         if (this.namespace != null) {
            lmo.formParameters.put("Namespace", this.namespace);
         }

         if (this.metricName != null) {
            lmo.formParameters.put("MetricName", this.metricName);
         }

         for (Dimension dimension : this.dimensions) {
            lmo.formParameters.put("Dimensions.member." + dimensionIndex + ".Name", dimension.getName());
            lmo.formParameters.put("Dimensions.member." + dimensionIndex + ".Value", dimension.getValue());
            dimensionIndex++;
         }

         if (this.nextToken != null) {
            lmo.formParameters.put("NextToken", this.nextToken);
         }

         return lmo;
      }
   }

}
