//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2012.02.08 at 02:47:44 PM GMT
//


package org.jclouds.vcloud.director.v1_5.domain.cim;

import javax.xml.bind.JAXBElement;
import javax.xml.namespace.QName;

public class ResourceAllocationCaption
    extends JAXBElement<ResourceAllocationCaptionType>
{

    protected final static QName NAME = new QName("http://schemas.dmtf.org/wbem/wscim/1/cim-schema/2/CIM_ResourceAllocationSettingData", "Caption");

    public ResourceAllocationCaption(ResourceAllocationCaptionType value) {
        super(NAME, ((Class) ResourceAllocationCaptionType.class), null, value);
    }

    public ResourceAllocationCaption() {
        super(NAME, ((Class) ResourceAllocationCaptionType.class), null, null);
    }

}
