/**
 * Licensed to jclouds, Inc. (jclouds) under one or more
 * contributor license agreements.  See the NOTICE file
 * distributed with this work for additional information
 * regarding copyright ownership.  jclouds licenses this file
 * to you under the Apache License, Version 2.0 (the
 * "License"); you may not use this file except in compliance
 * with the License.  You may obtain a copy of the License at
 *
 *   http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing,
 * software distributed under the License is distributed on an
 * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 * KIND, either express or implied.  See the License for the
 * specific language governing permissions and limitations
 * under the License.
 */
package org.jclouds.cloudwatch.domain;

import com.google.common.base.Preconditions;
import com.google.common.collect.Sets;
import org.jclouds.javax.annotation.Nullable;

import java.util.Date;
import java.util.Set;

/**
 * @see <a href="http://docs.amazonwebservices.com/AmazonCloudWatch/latest/APIReference/API_MetricDatum.html" />
 *
 * @author Jeremy Whitlock
 */
public class MetricDatum {

   private final Set<Dimension> dimensions;
   private final String metricName;
   private final StatisticSet statisticSet;
   private final Date timestamp;
   private final Unit unit;
   private final Double value;

   /**
    * Private constructor to enforce using {@link Builder}.
    */
   private MetricDatum(@Nullable Set<Dimension> dimensions, String metricName, StatisticSet statisticSet,
                       @Nullable Date timestamp, Unit unit, Double value) {
      // Default to an empty set
      if (dimensions == null) {
         this.dimensions = Sets.newLinkedHashSet();
      } else {
         this.dimensions = dimensions;
      }
      this.metricName = metricName;
      this.statisticSet = statisticSet;
      this.timestamp = timestamp;
      this.unit = unit;
      this.value = value;
   }

   /**
    * return the list of dimensions describing the the metric.
    */
   @Nullable
   public Set<Dimension> getDimensions() {
      return dimensions;
   }

   /**
    * return the metric name for the metric.
    */
   public String getMetricName() {
      return metricName;
   }

   /**
    * return the object describing the set of statistical values for the metric  (This and value are mutually
    * exclusive.)
    */
   public StatisticSet getStatisticSet() {
      return statisticSet;
   }

   /**
    * return the time stamp used for the metric
    */
   @Nullable
   public Date getTimestamp() {
      return timestamp;
   }

   /**
    * return Standard unit used for the metric.
    */
   public Unit getUnit() {
      return unit;
   }

   /**
    * return the actual value of the metric  (This and statisticSet are mutually exclusive.)
    *
    */
   public Double getValue() {
      return value;
   }

   /**
    * Returns a new builder. The generated builder is equivalent to the builder
    * created by the {@link Builder} constructor.
    */
   public static Builder builder() {
      return new Builder();
   }

   public static class Builder {

      private Set<Dimension> dimensions = Sets.newLinkedHashSet();
      private String metricName;
      private StatisticSet statisticSet;
      private Date timestamp;
      private Unit unit;
      private Double value;

      /**
       * Creates a new builder. The returned builder is equivalent to the builder
       * generated by {@link org.jclouds.cloudwatch.domain.MetricDatum#builder}.
       */
      public Builder() {}

      /**
       * A list of dimensions describing qualities of the metric.  (Set can be 10 or less items.)
       *
       * @param dimensions the dimensions describing the qualities of the metric
       *
       * @return this {@code Builder} object
       *
       * @throws IllegalArgumentException if the passed in dimensions has more than 10 members
       */
      public Builder dimensions(Set<Dimension> dimensions) {
         if (dimensions != null) {
            Preconditions.checkArgument(dimensions.size() <= 10, "dimensions can have 10 or fewer members.");
            this.dimensions = dimensions;
         }
         return this;
      }

      /**
       * A dimension describing qualities of the metric.  (Can be called multiple times up to a maximum of 10 times.)
       *
       * @param dimension the dimension describing the qualities of the metric
       *
       * @return this {@code Builder} object
       *
       * @throws IllegalArgumentException if the number of dimensions would be greater than 10 after adding
       */
      public Builder dimension(Dimension dimension) {
         if (dimension != null) {
            Preconditions.checkArgument(dimensions.size() < 10, "dimension member maximum count of 10 exceeded.");
            this.dimensions.add(dimension);
         }
         return this;
      }

      /**
       * The name of the metric.  (Should be called once.  Subsequent calls will overwrite the previous value.)
       *
       * @param metricName the metric name
       *
       * @return this {@code Builder} object
       *
       * @throws NullPointerException if metricName is null
       * @throws IllegalArgumentException if metricName is empty
       */
      public Builder metricName(String metricName) {
         Preconditions.checkNotNull(metricName, "metricName cannot be null.");
         Preconditions.checkArgument(metricName.length() > 1, "metricName must not be empty.");
         this.metricName = metricName;
         return this;
      }

      /**
       * The object describing the set of statistical values describing the metric.  (Should be called once.  Subsequent
       * calls will overwrite the previous value.  Also, this cannot be set once you've set the value.)
       *
       * @param statisticSet the object describing the set of statistical values for the metric
       *
       * @return this {@code Builder} object
       *
       * @throws NullPointerException if statisticSet is null
       * @throws IllegalArgumentException if value has already been set
       */
      public Builder statisticSet(StatisticSet statisticSet) {
         Preconditions.checkArgument(value == null, "value and statisticSet are mutually exclusive");
         this.statisticSet = statisticSet;
         return this;
      }

      /**
       * The time stamp used for the metric.  If not specified, the default value is set to the time the metric data was
       * received.  (Should be called once.  Subsequent calls will overwrite the previous value.)
       *
       * @param timestamp the time stamp used for the metric
       *
       * @return this {@code Builder} object
       */
      public Builder timestamp(Date timestamp) {
         this.timestamp = timestamp;
         return this;
      }

      /**
       * The unit for the metric.  (Should be called once.  Subsequent calls will overwrite the previous value.)
       *
       * @param unit the unit for the metric
       *
       * @return this {@code Builder} object
       *
       * @throws NullPointerException if unit is null
       */
      public Builder unit(Unit unit) {
         Preconditions.checkNotNull(unit, "unit cannot be null.");
         this.unit = unit;
         return this;
      }

      /**
       * The value for the metric.  (Should be called once.  Subsequent calls will overwrite the previous value.  Also,
       * this cannot be set once you've set the statisticValue.)
       *
       * @param value the value for the metric
       *
       * @return this {@code Builder} object
       *
       * @throws IllegalArgumentException if statisticSet has already been set
       */
      public Builder value(Double value) {
         Preconditions.checkArgument(statisticSet == null, "statisticSet and value are mutually exclusive");
         this.value = value;
         return this;
      }

      /**
       * Returns a newly-created {@code MetricDatum} based on the contents of the {@code Builder}.
       *
       * @throws NullPointerException if any of the required fields are null
       * @throws IllegalArgumentException if any of the provided fields don't meet required criteria
       */
      public MetricDatum build() {
         Preconditions.checkNotNull(metricName, "metricName cannot be null.");
         Preconditions.checkNotNull(unit, "unit cannot be null.");
         Preconditions.checkArgument(metricName.length() > 1 && metricName.length() <= 255,
                                     "metricName cannot be empty and must be 255 characters or less.");
         Preconditions.checkArgument(statisticSet != null || value != null,
                                     "statisticSet or value must be set");

         return new MetricDatum(dimensions, metricName, statisticSet, timestamp, unit, value);
      }

   }

}
