//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2012.02.08 at 02:47:44 PM GMT
//


package org.jclouds.vcloud.director.v1_5.domain.ovf;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;

import org.jclouds.vcloud.director.v1_5.domain.cim.CIMResourceAllocationSettingDataType;


/**
 * Wrapper for CIM_ResourceAllocationSettingData_Type
 *
 * <pre>
 * &lt;complexType name="RASD_Type" /&gt;
 * </pre>
 *
 * @author grkvlt@apache.org
 */
@XmlType(name = "RASD_Type")
public class RASD extends CIMResourceAllocationSettingDataType {

    @XmlAttribute(namespace = "http://schemas.dmtf.org/ovf/envelope/1")
    protected Boolean required;
    @XmlAttribute(namespace = "http://schemas.dmtf.org/ovf/envelope/1")
    protected String configuration;
    @XmlAttribute(namespace = "http://schemas.dmtf.org/ovf/envelope/1")
    protected String bound;

    /**
     * Gets the value of the required property.
     *
     * @return
     *     possible object is
     *     {@link Boolean }
     *
     */
    public boolean isRequired() {
        if (required == null) {
            return true;
        } else {
            return required;
        }
    }

    /**
     * Sets the value of the required property.
     *
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *
     */
    public void setRequired(Boolean value) {
        this.required = value;
    }

    /**
     * Gets the value of the configuration property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getConfiguration() {
        return configuration;
    }

    /**
     * Sets the value of the configuration property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setConfiguration(String value) {
        this.configuration = value;
    }

    /**
     * Gets the value of the bound property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getBound() {
        return bound;
    }

    /**
     * Sets the value of the bound property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setBound(String value) {
        this.bound = value;
    }

}
