package org.jclouds.aws.codegen.util;

import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileReader;

import org.jclouds.aws.codegen.model.Model;

import com.google.gson.Gson;
import com.google.gson.JsonParseException;

/**
 * TODO: Finish this class and document it.
 * 
 * 
 * @author James Murty
 */
public class CodeGenerator {
	
	/**
	 * Parses a JSON object model file (as generated by
	 * <tt>aws/src/main/bin/parse_ec2.pl</tt>) and converts
	 * it into a Java object graph. 
	 * 
	 * @param objectModelFile
	 * @return
	 * @throws JsonParseException
	 * @throws FileNotFoundException
	 */
	public Model parseModelFromJSON(File objectModelFile) 
		throws JsonParseException, FileNotFoundException 
	{
		Gson gson = new Gson();
		return gson.fromJson(new FileReader(objectModelFile), Model.class);				
	}
	
	public void generateCode(File objectModelFile, String rootPackageName) 
		throws JsonParseException, FileNotFoundException 
	{
		Model model = parseModelFromJSON(objectModelFile);
	}
	

	public static void main(String[] args) throws Exception {
		if (args.length != 2) {
			System.out.println("Usage: CodeGenerator objectModelFile rootPackage");
			System.out.println("  E.g: CodeGenerator ec2.json org.jclouds.aws.ec2");
			System.exit(1);
		}
		
		CodeGenerator codeGenerator = new CodeGenerator();
		codeGenerator.generateCode(new File(args[0]), args[1]);
	}
	
}
